### PR TITLE
Tog changes march 2015 on

### PR DESCRIPTION
**Pull request by tog22**
Discussed with Ryan, just like before.

### CODE REVIEW

**Comment by wezm** [comment]
Hi tog,

I would suggest that you remove all the `/* tog  */` comments. The git history tracks who made what changes so there no need for these.

**Comment by tog22** [comment]
I've been a little busy for that ;) Can we skip it? I'll remove the
comments in my next commit.

**Comment by wezm** [comment]
`%s/ \/\* tog[^/]\+\///` job done

**Comment by wezm** [comment]
And deployed

**Pull request merged**
