### PR TITLE
Replace Reddit footer link with link to FAQ.

### PR DESCRIPTION
**Pull request by patbl**
I'll update this when we know what the URL is.

footer

### CODE REVIEW

**Comment by wezm** [comment]
I don't think this is in the spirit of the Reddit open source licence and would recommend leaving it there. https://github.com/reddit/reddit/blob/master/LICENSE#L498

**Comment by patbl** [comment]
Good point; I was oblivious to that requirement.

I added it back. I'd be open to other ways of arranging the items.

footer

**Comment by patbl** [comment]
This is good to go.

**Comment by tog22** [comment]
Hey @moggyboy, we don't see the 'FAQ' link in @patbl's image above on http://effective-altruism.com/ . Is there anything more you or we need to do? 😄

**Comment by moggyboy** [comment]
Hi guys - this has been merged but not deployed. The support guys struggled a bit with the environment setup on Friday. I'll chase it up with them today.

**Comment by moggyboy** [comment]
@dangalipo Can you please get this deployed when you're back on deck?

**Comment by trike-support** [comment]
Hi Dan,

Can I archive this feed?

Thanks,
Pawel

**Pull request merged**
