### PR TITLE
Upgrade TinyMCE

### PR DESCRIPTION
**Pull request by patbl**
Needs tested.

Before:

tinymce3

After:

tinymce4-2
tinymce-inline
tinymce4-4
tinymce-alignment

### CODE REVIEW

**Comment by peterhurford** [comment]
This seems like a good idea and I dig all the code being removed. Any idea how we can effectively QA?

**Comment by patbl** [comment]
I think it looks as though a lot of code was removed because we had both the development and minified versions of each TinyMCE file previously, and I included just the minified files for the upgrade. There's a ton of code in there (plug-ins, themes, etc.) that we're not using, but it doesn't seem worth deleting because I'm pretty sure it's loaded only if we include it in `tinyMCE.init`.

I did a bit of testing and things seem to work. The upgrade shouldn't affect old articles at all unless people edit them. I also tried copy HTML from the production site into the editor and submitting it, and that also worked fine.

I don't know how exhaustively we need to test this, but my sense is that it wouldn't be terrible to let users test it. Regular users would notice the new editor and might report bugs if they were annoying enough.

It might be a good idea to add a message to the article-editing page that says something like, "We recently upgraded the editor used on this page. Please contact Patrick at pbrinichlanglois@gmail.com if you have any problems formatting or saving articles."

**Comment by peterhurford** [comment]
Ok, I suppose we can merge/deploy and then revert is people complain? @patbl 

We can write an EA Forum post about it so people know what's new.

**Comment by patbl** [comment]
Yes, that sounds like a good idea. I'll do a bit more testing, then let you all know when it's ready.

**Comment by patbl** [comment]
I added an upgrade message:

upgrade-message

I put my e-mail address on there. I think I'd be pretty good about creating a GitHub issue promptly (not necessarily about fixing it, though).

**Comment by patbl** [comment]
I guess this is good to go!

**Comment by peterhurford** [comment]
Cool, I contacted Trike about it.

**Comment by moggyboy** [comment]
This is live.

**Pull request merged**
